[package]
name = "risc0-core"
description = "Core types for RISC Zero crates"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
bytemuck = { version = "1.12", default-features=false, features = ["derive"] }
rand_core = "0.6"

[dev-dependencies]
rand = { version = "0.8", default-features=false,features = ["small_rng"] }

[features]
std = []
